/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bismillah;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Husnul Hidayat
 */
public class penjualanForm extends javax.swing.JFrame {

    /**
     * Creates new form penjualanForm
     */
    public penjualanForm() {
        initComponents();
        data_untuk_combo();
    }

    private void data_untuk_combo(){
    try {        
        comboPembeli.removeAllItems();
        
            Connection c=database.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select nama from pelanggan group by ID";
            ResultSet r=s.executeQuery(sql);    
            while (r.next()) {
                comboPembeli.addItem(r.getString("nama"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nopolField = new javax.swing.JTextField();
        beliBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cicilanField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        perbulanField = new javax.swing.JTextField();
        comboPembeli = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelmerk = new javax.swing.JLabel();
        labeljens = new javax.swing.JLabel();
        labelharga = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Masukkan No. Polis :");

        nopolField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nopolFieldCaretUpdate(evt);
            }
        });

        beliBtn.setText("Beli");
        beliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Pembeli    :");

        jLabel3.setText("Cicilan :");

        jLabel4.setText("Perbulan :");

        comboPembeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPembeliActionPerformed(evt);
            }
        });

        jLabel5.setText("Merk :");

        jLabel6.setText("Jenis :");

        jLabel7.setText("Harga : ");

        labelmerk.setText("-");

        labeljens.setText("-");

        labelharga.setText("-");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cicilanField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(perbulanField)
                                    .addComponent(comboPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(nopolField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(labelmerk))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelharga)
                                            .addComponent(labeljens)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(beliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nopolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelmerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labeljens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelharga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cicilanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(perbulanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beliBtn)
                    .addComponent(jButton1))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPembeliActionPerformed
        // TODO add your handling code here:
         int i=comboPembeli.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) comboPembeli.getSelectedItem();
            Connection c=database.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from pelanggan WHERE nama=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            }catch(SQLException e){
            System.out.println(e);        
         }
    }//GEN-LAST:event_comboPembeliActionPerformed

    private void nopolFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nopolFieldCaretUpdate
        // TODO add your handling code here:
           try {                
            String nopol=(String) this.nopolField.getText();
            Connection c=database.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from data Where nopol='"+nopol+"' ";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next()){
                this.labelmerk.setText(r.getString("merk"));
                this.labeljens.setText(r.getString("jenis"));
                this.labelharga.setText(r.getString("harga"));    
               
            }else{
                this.labelmerk.setText("Unknown");
                this.labeljens.setText("Unknown");
                this.labelharga.setText("Unknown");

            }         
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "OK");
        }
    }//GEN-LAST:event_nopolFieldCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        home(); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void home(){
        mainForm t=new mainForm();                  
        t.setVisible(true);
        this.dispose(); 
    }
    
    private void beliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBtnActionPerformed
        // TODO add your handling code here:
        Penjualan p = new Penjualan();
        p.setNopol(nopolField.getText());
        p.setMerk(labelmerk.getText());
        p.setJenis(labeljens.getText());
        p.setHarga(Integer.parseInt(labelharga.getText()));
        p.setNama(comboPembeli.getSelectedItem().toString());
        p.setCicilan(cicilanField.getText());
        p.setPerbulan(Integer.parseInt(perbulanField.getText()));
        p.savePenjualan();
        nopolField.setText("");
        labelmerk.setText("");
        labelharga.setText("");
        comboPembeli.setToolTipText("");
        cicilanField.setText("");
        perbulanField.setText("");
        
        int confirm = JOptionPane.showConfirmDialog(this,"Apakah anda yakin?");
        if (confirm == JOptionPane.YES_OPTION) {
           JOptionPane.showMessageDialog(this, "Terimakasih "+comboPembeli.getSelectedItem()+", Pembelian Kendaraan dengan\n ------------------------ \n Nomor Polisi : "+nopolField.getText()+"\nMerk : "+labelmerk.getText()+"\nJenis : "+labeljens.getText()+"\nHarga : "+labelharga.getText()+"\nCicilan : "+cicilanField.getText()+"\nPerbulan : "+perbulanField.getText()+"\n ------------------------ \nTelah berhasil!");
           home();
        }
        else{
            JOptionPane.showMessageDialog(this, "Pemebelian dibatalkan");
            home();
        }
    }//GEN-LAST:event_beliBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliBtn;
    private javax.swing.JTextField cicilanField;
    private javax.swing.JComboBox<String> comboPembeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelharga;
    private javax.swing.JLabel labeljens;
    private javax.swing.JLabel labelmerk;
    private javax.swing.JTextField nopolField;
    private javax.swing.JTextField perbulanField;
    // End of variables declaration//GEN-END:variables
}
